### ISSUE TITLE
How can we generate the streaming URL with just a 7digital track ID?

### ISSUE THREAD

**Issue by PradatiusD** [7digital/7digital-iOS-SDK#5]
Hi 7digital iOS SDK devs,

Due to the fact that our playlist recommendation engine comes from Senzari (which just returns a list of 7digital track IDs), we can't start from a **SDAPIRequest** and do something like:
```obj-c
SDTrack *track = [self.sdRelease.tracks objectAtIndex:indexPath.row];
NSURL *trackURL = [SDMedia urlForTrack:track mediaType: kSDMediaTypeStreamingInternetRadio];
```
That brings us the the following question:

If we just had a 7digtal track ID, how can we recast that ID into an SDTrack so that we can correctly generate the NSURL needed for music playback?

Thanks,
Daniel

**Comment by mmmbiscuits** [comment]
Hey sorry I didn't see this earlier.

The method urlForTrack only really uses the trackId property from SDTrack (except for in the case of a download) so in your case im pretty sure you can just initialise a SDTrack like so.

```
SDTrack * track = [[SDTrack alloc]init];
track.trackId = 1234;
```

Theres also now an new method to generate stream url's thats been added to the SDK. within the SDStreamTrackUrl class which will take the track id and return a suitable NSUrl.

Hopefully that helps.

**Comment by PradatiusD** [comment]
It did!  That is exactly what we ended up doing earlier in January.  But thanks for replying!
